services:
    dds-monitor:
        image: dds-monitor:1.0
        network_mode: host
        ipc: host
        volumes:
          - ./run.sh:/run.sh
        command: ["/bin/bash", "-c" , "/run.sh"]
        tty: true
