version: '2.4'
services:
    dds-monitor:
        hostname: dds-monitor
        image: dds-monitor
        network_mode: host
        ipc: host
        volumes:
          - ./run.sh:/run.sh
        command: ["/bin/bash", "-c" , "/run.sh"]
        tty: true
