services:
  dds-monitor:
    container_name: dds-monitor
    image: dds-monitor:amd-1.2
    network_mode: host
    ipc: host
    volumes:
      - ./run.sh:/run.sh
    command: ["/bin/bash", "-c" , "/run.sh"]
    tty: true
